/**
 * File:        apps/web/gql/operations/oms/cancelBracketGroup.ts
 * Module:      web · GraphQL · OMS Operations
 * Purpose:     Codegen target for CancelBracketGroup mutation.
 *              This file is the TypeScript wrapper around the GraphQL operation.
 *              Generated by codegen — do not edit manually.
 *
 * Exports:
 *   - CancelBracketGroupDocument — gql document for the mutation
 *   - CancelBracketGroupMutation — response type
 *   - CancelBracketGroupMutationVariables — input variables type
 *   - useCancelBracketGroupMutation — Apollo mutation hook
 *
 * Depends on:
 *   - @apollo/client — gql, useMutation
 *   - ../../generated/graphql — Scalars, Exact, InputMaybe types
 *
 * Side-effects:
 *   - Network I/O via Apollo Client
 *
 * Key invariants:
 *   - parentOrderId must refer to a PRIMARY order with active bracket children
 *
 * Author:      BharatERP
 * Last-updated: 2026-05-30
 */

import * as Types from '../../generated/graphql';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type CancelBracketGroupMutationVariables = Types.Exact<{
  parentOrderId: Types.Scalars['ID']['input'];
}>;

export type CancelBracketGroupMutation = { __typename?: 'Mutation', cancelBracketGroup?: { __typename?: 'OrderEntity', id: string, clientOrderId: string, status: string, updatedAt: string } | null };

export const CancelBracketGroupDocument = gql`
    mutation CancelBracketGroup($parentOrderId: ID!) {
  cancelBracketGroup(parentOrderId: $parentOrderId) {
    id
    clientOrderId
    status
    updatedAt
  }
}
    `;
export type CancelBracketGroupMutationFn = Apollo.MutationFunction<CancelBracketGroupMutation, CancelBracketGroupMutationVariables>;

/**
 * __useCancelBracketGroupMutation__
 *
 * To run a mutation, you first call `useCancelBracketGroupMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCancelBracketGroupMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [cancelBracketGroupMutation, { data, loading, error }] = useCancelBracketGroupMutation({
 *   variables: {
 *      parentOrderId: // value for 'parentOrderId'
 *   },
 * });
 */
export function useCancelBracketGroupMutation(baseOptions?: Apollo.MutationHookOptions<CancelBracketGroupMutation, CancelBracketGroupMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CancelBracketGroupMutation, CancelBracketGroupMutationVariables>(CancelBracketGroupDocument, options);
      }
export type CancelBracketGroupMutationHookResult = ReturnType<typeof useCancelBracketGroupMutation>;
export type CancelBracketGroupMutationResult = Apollo.MutationResult<CancelBracketGroupMutation>;
export type CancelBracketGroupMutationOptions = Apollo.BaseMutationOptions<CancelBracketGroupMutation, CancelBracketGroupMutationVariables>;
