query GetOrders($accountId: ID, $status: String, $side: String, $limit: Int, $offset: Int) {
  orders(accountId: $accountId, status: $status, side: $side, limit: $limit, offset: $offset) {
    data {
      id
      clientOrderId
      externalRefId
      instrumentId
      side
      type
      quantity
      filledQty
      remainingQty
      price
      slPrice
      tpPrice
      status
      timeInForce
      createdAt
      updatedAt
      triggerPrice
      triggerCondition
      algoType
    }
    total
    limit
    offset
  }
}