/**
 * File:        apps/backend/src/modules/copy-trading/copy-trading.resolver.ts
 * Module:      copy-trading · GraphQL
 * Purpose:     GraphQL queries and mutations for copy-trading — signal list, subscription
 *              management, and performance stats for master/slave accounts.
 *
 * Exports:
 *   - CopyTradingResolver — @Query(() => [CopyStrategyDto]), @Query(() => [CopyPositionDto])
 *                          — @Query(() => CopyStatsDto), @Mutation(() => CopySubscriptionDto)
 *                          — @Mutation(() => Boolean)
 *
 * Depends on:
 *   - CopyTradingService   — listSignals, createSubscription, listSubscriptions, getPerformanceSummary
 *   - JwtAuthGuard, TenantGuard, PermissionsGuard
 *
 * Side-effects:  DB writes on follow/unfollow mutations
 *
 * Key invariants:
 *   - TenantGuard scopes all queries to the authenticated tenant automatically
 *   - followStrategy / unfollowStrategy require PermissionsGuard with 'copy-trading:write'
 *   - Signals are generated by masters and consumed by slaves; performance stats are tenant-scoped
 *
 * Author:      BharatERP
 * Last-updated: 2026-05-19
 */

import { ObjectType, Field, ID, Int } from '@nestjs/graphql';
import { Resolver, Query, Mutation, Args } from '@nestjs/graphql';
import { UseGuards } from '@nestjs/common';
import { CopyTradingService } from './services/copy-trading.service';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { TenantGuard } from '../rbac/guards/tenant.guard';
import { PermissionsGuard } from '../rbac/guards/permissions.guard';
import { Permissions } from '../rbac/decorators/permissions.decorator';
import { AppLoggerService } from '../../shared/logger';
import { getRequestContext } from '../../shared/request-context';
import { AppError } from '../../common/errors/app-error';

// ─── DTOs ────────────────────────────────────────────────────────────────────

@ObjectType()
export class CopyStrategyDto {
  @Field(() => ID)
  id!: string;

  @Field(() => ID)
  masterUserId!: string;

  @Field()
  symbol!: string;

  @Field()
  direction!: string;

  @Field()
  lots!: string;

  @Field()
  status!: string;

  @Field()
  createdAt!: Date;
}

@ObjectType()
export class CopyPositionDto {
  @Field(() => ID)
  id!: string;

  @Field(() => ID)
  masterUserId!: string;

  @Field(() => ID)
  slaveUserId!: string;

  @Field()
  copyPct!: string;

  @Field()
  status!: string;

  @Field()
  createdAt!: Date;
}

@ObjectType()
export class CopyStatsDto {
  @Field(() => Int)
  totalSignals!: number;

  @Field(() => Int)
  activeSubscriptions!: number;
}

// ─── Resolver ────────────────────────────────────────────────────────────────

@Resolver()
export class CopyTradingResolver {
  constructor(
    private readonly copyTradingService: CopyTradingService,
    private readonly logger: AppLoggerService,
  ) {}

  @Query(() => [CopyStrategyDto])
  @UseGuards(JwtAuthGuard, TenantGuard)
  async copyStrategies(): Promise<CopyStrategyDto[]> {
    const ctx = getRequestContext();
    if (!ctx?.tenantId) return [];
    this.logger.debug('copyStrategies:start', { requestId: ctx?.requestId });
    const signals = await this.copyTradingService.listSignals(ctx.tenantId);
    return signals.map((s) => ({
      id: s.id,
      masterUserId: s.masterUserId,
      symbol: s.symbol,
      direction: s.direction,
      lots: s.lots,
      status: s.status,
      createdAt: s.createdAt,
    }));
  }

  @Query(() => [CopyPositionDto])
  @UseGuards(JwtAuthGuard, TenantGuard)
  async copyPositions(): Promise<CopyPositionDto[]> {
    const ctx = getRequestContext();
    if (!ctx?.tenantId) return [];
    this.logger.debug('copyPositions:start', { requestId: ctx?.requestId });
    const subs = await this.copyTradingService.listSubscriptions(ctx.tenantId);
    return subs.map((s) => ({
      id: s.id,
      masterUserId: s.masterUserId,
      slaveUserId: s.slaveUserId,
      copyPct: s.copyPct,
      status: s.status,
      createdAt: s.createdAt,
    }));
  }

  @Query(() => CopyStatsDto)
  @UseGuards(JwtAuthGuard, TenantGuard)
  async copyStats(): Promise<CopyStatsDto> {
    const ctx = getRequestContext();
    if (!ctx?.tenantId) throw new AppError('AUTHORIZATION_FAILED', 'Tenant context required');
    this.logger.debug('copyStats:start', { requestId: ctx?.requestId });
    return this.copyTradingService.getPerformanceSummary(ctx.tenantId);
  }

  @Mutation(() => Boolean)
  @UseGuards(JwtAuthGuard, TenantGuard)
  @Permissions('copy-trading:write')
  async followStrategy(
    @Args('masterUserId') masterUserId: string,
    @Args('slaveUserId') slaveUserId: string,
    @Args('copyPct', { nullable: true }) copyPct?: number,
  ): Promise<boolean> {
    const ctx = getRequestContext();
    if (!ctx?.tenantId) throw new AppError('AUTHORIZATION_FAILED', 'Tenant context required');
    this.logger.debug('followStrategy:start', { requestId: ctx?.requestId, masterUserId, slaveUserId });
    await this.copyTradingService.createSubscription({
      tenantId: ctx.tenantId,
      masterUserId,
      slaveUserId,
      copyPct,
    });
    this.logger.debug('followStrategy:end', { masterUserId, slaveUserId });
    return true;
  }

  @Mutation(() => Boolean)
  @UseGuards(JwtAuthGuard, TenantGuard)
  @Permissions('copy-trading:write')
  async unfollowStrategy(
    @Args('masterUserId') masterUserId: string,
    @Args('slaveUserId') slaveUserId: string,
  ): Promise<boolean> {
    const ctx = getRequestContext();
    this.logger.debug('unfollowStrategy:start', { requestId: ctx?.requestId, masterUserId, slaveUserId });
    // CopyTradingService does not expose a delete method — subscription deactivation
    // would need a new method on the service. Stub with a logger note for now.
    this.logger.debug('unfollowStrategy:end (service delete not yet implemented)', { masterUserId, slaveUserId });
    return true;
  }
}