/**
 * File:        apps/web/gql/hooks/useConsoleUser.ts
 * Module:      web · GraphQL · Hooks
 * Purpose:     Aggregator hook for the /console user payload. Calls the
 *              backend's getMe + getUserProfile + getMyAccounts queries,
 *              maps the DTOs to the ConsoleUser shape via mappers.ts, and
 *              returns a complete result with loading/error/refetch.
 *
 * Exports:
 *   - useConsoleUser()  → ConsoleUser     — same shape as before (back-compat)
 *   - useConsoleUserStatus() → { loading, error, refetch, isAuthenticated }
 *   - UseConsoleUserResult — type
 *
 * Depends on:
 *   - @/gql/generated/hooks  — useGetMeQuery, useGetUserProfileQuery, useGetMyAccountsQuery
 *   - @/gql/client/cookie    — getCookie (auth detection)
 *   - @/features/console/lib/mappers  — pure DTO → ConsoleUser transformers
 *   - @/features/console/lib/seed-data — SEED_USER fallback
 *
 * Side-effects:
 *   - Reads httpOnly `access_token` cookie (read-only)
 *   - Triggers GraphQL queries when authenticated
 *
 * Key invariants:
 *   - When unauthenticated (no token), all queries are skipped and SEED_USER
 *     is returned unchanged — design preview keeps working.
 *   - When authenticated but any sub-query fails, partial data is filled in
 *     from the seed fallback. The error is surfaced via useConsoleUserStatus()
 *     for banners; the user object is never partially-shaped (no `undefined`s).
 *   - The returned `ConsoleUser` reference changes only when a sub-query
 *     succeeds with new data — sections can memoize against it.
 *
 * Author:       BharatERP
 * Last-updated: 2026-06-09
 */

import { useMemo, useCallback } from 'react';
import { getCookie } from '../client/cookie';
import {
  useGetMeQuery,
  // These will be generated by `npm run codegen:web` from the new .gql files.
  // They're typed as `any` until that runs; the wrapper functions below narrow
  // the result to the mapper's expected shape.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} from '../generated/hooks';
import type { ConsoleUser } from '@/features/console/lib/seed-data';
import {
  mapProfileToConsoleUser,
  emptyConsoleUser,
  type BackendUserProfile,
  type BackendAccount,
} from '@/features/console/lib/mappers';

// ─────────────────────────────────────────────────────────────────────────────
// Auth detection — the same signal the Apollo auth-link uses to decide whether
// to inject the Bearer header. Read in render so the hook tracks login state
// via cookie changes (rare, but a logout that clears the cookie should
// immediately stop queries).
// ─────────────────────────────────────────────────────────────────────────────

function useIsAuthenticated(): boolean {
  // Reading the cookie on every render is cheap (document.cookie is sync).
  // We re-read on each render so logout via cookie-clear takes effect.
  return typeof document !== 'undefined' && !!getCookie('access_token');
}

// ─────────────────────────────────────────────────────────────────────────────
// Narrowing helper: cast an `any`-typed generated hook result to the mapper's
// expected shape. The generated hooks are tightly typed, but until codegen
// has run for the new .gql files we keep the import dynamic.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Use the generated profile query. Falls back to `useGetMeQuery` until the
 * new codegen output lands. The mapping is the same — `me` returns
 * `{ userId, tenantId }` and we treat it as a minimal profile.
 */
function useProfileAndAccounts(hasToken: boolean): {
  profile: BackendUserProfile | null;
  accounts: ReadonlyArray<BackendAccount>;
  loading: boolean;
  error?: Error;
  refetchProfile: () => Promise<unknown>;
  refetchAccounts: () => Promise<unknown>;
} {
  // `me` gives us the userId+tenantId. We use it as the entry point and
  // run a follow-up `user(id)` query for the full profile.
  const meQ = useGetMeQuery({
    skip: !hasToken,
    errorPolicy: 'all',
    fetchPolicy: 'cache-and-network',
  });

  // The generated hook for getUserProfile is `useGetUserProfileQuery`.
  // Until codegen runs, the import is dynamic and the result is unknown.
  // We try to use it via a module-level lazy require so the build doesn't
  // break before codegen.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let profileQ: any = { data: null, loading: false, error: undefined, refetch: () => Promise.resolve() };
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let accountsQ: any = { data: null, loading: false, error: undefined, refetch: () => Promise.resolve() };

  try {
    // Dynamic require so missing exports (pre-codegen) don't crash the build.
    // eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
    const generated = require('../generated/hooks');
    if (typeof generated.useGetUserProfileQuery === 'function') {
      profileQ = generated.useGetUserProfileQuery({
        variables: { userId: meQ.data?.me?.userId ?? '' },
        skip: !hasToken || !meQ.data?.me?.userId,
        errorPolicy: 'all',
        fetchPolicy: 'cache-and-network',
      });
    }
    if (typeof generated.useGetMyAccountsQuery === 'function') {
      accountsQ = generated.useGetMyAccountsQuery({
        skip: !hasToken,
        errorPolicy: 'all',
        fetchPolicy: 'cache-and-network',
      });
  }
  } catch {
    // Generated hooks not present yet — keep the no-op defaults above.
  }

  const profile: BackendUserProfile | null = useMemo(() => {
    const u = profileQ.data?.user;
    if (!u) return null;
    return {
      id: u.id,
      tenantId: u.tenantId,
      mobileE164: u.mobileE164,
      email: u.email ?? null,
      isMobileVerified: !!u.isMobileVerified,
      isEmailVerified: !!u.isEmailVerified,
      name: u.name ?? null,
      countryCode: u.countryCode ?? null,
      isActive: !!u.isActive,
      createdAt: u.createdAt,
    };
  }, [profileQ.data]);

  const accounts: ReadonlyArray<BackendAccount> = useMemo(() => {
    const list = accountsQ.data?.myAccounts;
    if (!Array.isArray(list)) return [];
    return list.map((a: BackendAccount) => ({
      id: a.id,
      accountType: a.accountType,
      status: a.status,
      baseCurrency: a.baseCurrency,
      createdAt: a.createdAt,
      updatedAt: a.updatedAt,
    }));
  }, [accountsQ.data]);

  const loading = !!meQ.loading || !!profileQ.loading || !!accountsQ.loading;
  const error: Error | undefined = meQ.error ?? profileQ.error ?? accountsQ.error;

  const refetchProfile = useCallback(
    () => Promise.resolve(profileQ.refetch?.()),
    [profileQ],
  );
  const refetchAccounts = useCallback(
    () => Promise.resolve(accountsQ.refetch?.()),
    [accountsQ],
  );

  return { profile, accounts, loading, error, refetchProfile, refetchAccounts };
}

// ─────────────────────────────────────────────────────────────────────────────
// Public hook: same signature as the old useConsoleUser — returns a ConsoleUser.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Console user data. Unauthenticated → returns emptyConsoleUser() (no fake
 * persona, no leaked IBANs). Authenticated with backend fields missing →
 * returns empty sentinels (NEVER the seed persona). Use useConsoleUserStatus()
 * to detect loading/error/refetch.
 */
export function useConsoleUser(): ConsoleUser {
  const hasToken = useIsAuthenticated();
  const { profile, accounts } = useProfileAndAccounts(hasToken);

  return useMemo(() => {
    if (!hasToken) return emptyConsoleUser();
    return mapProfileToConsoleUser(profile, accounts);
  }, [hasToken, profile, accounts]);
}

// ─────────────────────────────────────────────────────────────────────────────
// Status hook: for the shell's loading/error banner. Returns metadata only;
// calling it from a sibling component avoids re-running the mapping.
// ─────────────────────────────────────────────────────────────────────────────

export interface UseConsoleUserStatusResult {
  loading: boolean;
  error?: Error;
  isAuthenticated: boolean;
  refetch: () => Promise<unknown>;
}

export function useConsoleUserStatus(): UseConsoleUserStatusResult {
  const hasToken = useIsAuthenticated();
  const { loading, error, refetchProfile, refetchAccounts } = useProfileAndAccounts(hasToken);

  const refetch = useCallback(
    () => Promise.all([refetchProfile(), refetchAccounts()]),
    [refetchProfile, refetchAccounts],
  );

  return { loading, error, isAuthenticated: hasToken, refetch };
}
